name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - implement-new-jekyll-theme

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action
        with:
          token: ${{ secrets.TOKEN }}